version: '3.8'
services:
  graphql:
    container_name: graphql-go
    image: golang
    tty: true
    command: bash -c "go run cmd/server/server.go"
    working_dir: /usr/local/go/src/graph-ql
    volumes:
      - ../:/usr/local/go/src/graph-ql
    ports:
      - 8080:8080
