version: '3.8'
services:
  graphql:
    container_name: graphql-go
    image: golang
    tty: true
    command: bash -c "go run cmd/server/server.go"
    # command: bash
    working_dir: /usr/src
    volumes:
      - ..:/usr/src
    ports:
      - 8080:8080